// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnmdWzfY32ntCXvNI-OfSmB8xWm4tDwvQ',
    appId: '1:491316420371:web:e1352529326abd5dbc84e6',
    messagingSenderId: '491316420371',
    projectId: 'laundry-management-57453',
    authDomain: 'laundry-management-57453.firebaseapp.com',
    storageBucket: 'laundry-management-57453.firebasestorage.app',
    measurementId: 'G-F114J0SWHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC7wDFaKRWSDYM10aPFfoLmVf2sSjhuxQ',
    appId: '1:491316420371:android:dc2c598d35eb2cd0bc84e6',
    messagingSenderId: '491316420371',
    projectId: 'laundry-management-57453',
    storageBucket: 'laundry-management-57453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXiNKVWqHGIdauRiomI_Own_rqxOggyPE',
    appId: '1:491316420371:ios:12132e61f826a30bbc84e6',
    messagingSenderId: '491316420371',
    projectId: 'laundry-management-57453',
    storageBucket: 'laundry-management-57453.firebasestorage.app',
    iosBundleId: 'com.cloudironing.admin',
  );
}
